[2024-04-05 18:31:39,011: INFO: main: Let's go through log messages]
[2024-04-09 00:53:52,025:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 00:53:52,075:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 00:53:52,083:INFO:common:created directory at: artifacts]
[2024-04-09 00:53:52,087:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 00:54:53,301:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 00:54:53,304:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 00:54:53,307:INFO:common:created directory at: artifacts]
[2024-04-09 00:54:53,309:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 00:54:57,526:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 00:54:57,530:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 00:54:57,533:INFO:common:created directory at: artifacts]
[2024-04-09 00:54:57,536:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 00:57:31,567:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 00:57:31,569:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 00:57:31,571:INFO:common:created directory at: artifacts]
[2024-04-09 00:57:31,575:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 00:59:31,963:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 00:59:31,967:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 00:59:31,970:INFO:common:created directory at: artifacts]
[2024-04-09 00:59:31,974:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 01:00:49,908:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 01:00:49,910:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 01:00:49,913:INFO:common:created directory at: artifacts]
[2024-04-09 01:00:49,914:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 01:03:02,013:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 01:03:02,018:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 01:03:02,024:INFO:common:created directory at: artifacts]
[2024-04-09 01:03:02,027:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 01:03:02,030:INFO:986331348:Downloading data from https://drive.google.com/file/d/1h92EBFNYeVreVuYyjtATtkGu1iLTdFyt/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-09 01:06:22,834:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1h92EBFNYeVreVuYyjtATtkGu1iLTdFyt/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-09 01:23:10,777:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-09 01:23:10,779:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-09 01:23:10,781:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-09 01:23:10,782:INFO:common:created directory at: artifacts]
[2024-04-09 01:23:10,784:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-09 01:23:12,221:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Tue, 09 Apr 2024 08:23:12 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=LwEPaFfOgNfF8pT0FVr4F9PawWhGJefA8SKPi7Yc_HyyZiC2Z0eUkI-r2w1EfK8hvLwnGnhR9K6PZLSpbZLGKWSfwVwyu9Z8o0oIhowb16vcGAvt1IOnY7bhCedtsc18wdr9AspRD5aGKGJWA5A-QsgJwv-tvAbUIPMN4yFIxHU; expires=Wed, 09-Oct-2024 08:23:12 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-09 01:23:13,262:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-14 18:34:17,609:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-14 18:34:17,617:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-14 18:34:17,621:INFO:common:created directory at: artifacts]
[2024-04-14 18:34:17,623:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-14 18:34:17,625:INFO:986331348:Downloading data from https://drive.google.com/file/d/1h92EBFNYeVreVuYyjtATtkGu1iLTdFyt/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-14 18:37:36,419:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1h92EBFNYeVreVuYyjtATtkGu1iLTdFyt/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-14 18:53:17,058:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-14 18:53:17,067:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-14 18:53:17,068:INFO:common:created directory at: artifacts]
[2024-04-14 18:53:17,070:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-14 18:53:17,072:INFO:986331348:Downloading data from https://drive.google.com/file/d/1h92EBFNYeVreVuYyjtATtkGu1iLTdFyt/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-14 18:56:39,006:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1h92EBFNYeVreVuYyjtATtkGu1iLTdFyt/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-14 19:25:40,731:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-14 19:25:40,755:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-14 19:25:40,767:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-14 19:25:40,768:INFO:common:created directory at: artifacts]
[2024-04-14 19:25:40,769:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-14 19:25:41,795:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Mon, 15 Apr 2024 02:25:42 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=PjPystKwKl4mw4aYyKNg7XLbYYmHYXiV3giTpxy7-F0K6auc9h2sToj6h97d-UHDldSeJa_Iw0AhOoWcAsinnrmrevxBNiJvnezFLg2PFx2JQb9U_w2fjZgKTkgSNTG9vVjSQoKo3nkxReeaC50O7xqWUWHfdLFHAA1oERTFCAY; expires=Tue, 15-Oct-2024 02:25:42 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-14 19:25:41,895:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\zipfile.py", line 1271, in __init__
    self._RealGetContents()
  File "C:\Users\nandi\anaconda3\envs\covidenv\lib\zipfile.py", line 1338, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-14 19:29:16,584:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-14 19:29:16,586:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-14 19:29:16,586:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-14 19:29:16,587:INFO:common:created directory at: artifacts]
[2024-04-14 19:29:16,587:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-14 19:29:17,028:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Mon, 15 Apr 2024 02:29:17 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=ZSO_z9YG2K2uv7oUTjWtYmJg2PF3EOny5TrVVoq9R2puX8wwyIY9LAs-UckAAXg_tvYiNX1vsElPTmUbau6t7euArzRfkVJ-7XdHiJc83qGxNYP7cH5PZRwCAUDDX0dnkElAKz41eZLYfAhm5gmFJrGM4JSQUROdib_tB5ZUNPU; expires=Tue, 15-Oct-2024 02:29:17 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-14 19:29:17,159:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 16:49:32,428:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 16:49:32,440:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 16:49:32,450:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 16:49:32,451:INFO:common:created directory at: artifacts]
[2024-04-15 16:49:32,452:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 16:49:33,092:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Mon, 15 Apr 2024 23:49:33 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=TViLhMYUZOqDq3WMCe-dbC1RxI_VeH0DMh92on2xPqMu1o1m3eZFgWyX_w_c6QQIcYg5tCMA72uM9dj1X7Bwn5Fw9wtRZwUEMeVfCAFie5jwBVPIfNn8RZ15_smRBu4sVk8Wkblwb3MHEhqwiVy9kYlwIecfFBukfkbZjmlRTeo; expires=Tue, 15-Oct-2024 23:49:33 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-15 16:49:33,263:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 16:50:27,869:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 16:50:27,883:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 16:50:27,885:INFO:common:created directory at: artifacts]
[2024-04-15 16:50:27,887:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 16:50:27,889:INFO:986331348:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-15 16:53:47,744:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-15 17:05:56,593:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 17:05:56,594:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 17:05:56,595:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 17:05:56,596:INFO:common:created directory at: artifacts]
[2024-04-15 17:05:56,596:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 17:05:57,207:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Tue, 16 Apr 2024 00:05:57 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=M9V3In09hH0oTpB4Xiod9qElGVAe4H3EUj-iWtc4WAe6nQik34guXtRXd-ekN2R9qL4hTMk2R47B3czL3xQkhodWUKsyIEsGxwBFF_3CBOJb3Bl2qHuLwUzo43lQq6nEre9eHVJG1oqdfGkT5eqr5HhSBuBjZuuyglYLkwswsn4; expires=Wed, 16-Oct-2024 00:05:57 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-15 17:05:57,334:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 17:15:12,516:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 17:15:12,517:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 17:15:12,518:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 17:15:12,519:INFO:common:created directory at: artifacts]
[2024-04-15 17:15:12,519:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 17:15:13,078:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Tue, 16 Apr 2024 00:15:13 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=mCrcM6PHWI9LroHtrtfuf7Xr9zdwCssWBvD9TCbooFnTWs-VpnuW_XEbx0dYaCqUFChj9pxOFkXc7H-003GXrFblFuWCeGV972aDe545VO1glldJ_R6srDzXRK-Ic2EuAxYruajrGsJnA-aFTXeJhkKetA-Tp0dyYglFnpJ5c9Q; expires=Wed, 16-Oct-2024 00:15:13 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-15 17:15:13,208:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 17:15:43,729:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 17:15:43,730:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 17:15:43,731:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 17:15:43,733:INFO:common:created directory at: artifacts]
[2024-04-15 17:15:43,733:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 17:15:44,163:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Tue, 16 Apr 2024 00:15:44 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=J67FuaKM-KBD-7494FNgm-Pi_qRNLLBWSZkg-Bul3ec3KR_ZjJhtALVSnMT84vUTLhlH1i_HiC9dhEmSesSxdhfeduwqrGJ9NGmpzMW_zEdblfJ8D--Jbwb3l7B2fXWYeMCkoyzF5ajEQrDbF6G__z7KJP4uIQ_TOYlSR-cNkBA; expires=Wed, 16-Oct-2024 00:15:44 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-15 17:15:44,241:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 17:31:20,127:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 17:31:20,129:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 17:31:20,130:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 17:31:20,130:INFO:common:created directory at: artifacts]
[2024-04-15 17:31:20,131:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 17:31:20,131:INFO:data_ingestion:File already exists of size: ~ 83 KB]
[2024-04-15 17:31:20,134:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 17:31:44,637:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 17:31:44,638:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 17:31:44,639:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 17:31:44,640:INFO:common:created directory at: artifacts]
[2024-04-15 17:31:44,641:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 17:31:44,642:INFO:data_ingestion:File already exists of size: ~ 83 KB]
[2024-04-15 17:31:44,643:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-15 18:03:54,579:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-15 18:03:54,585:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-15 18:03:54,586:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-15 18:03:54,586:INFO:common:created directory at: artifacts]
[2024-04-15 18:03:54,586:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-15 18:03:55,199:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Tue, 16 Apr 2024 01:03:55 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=GDSOCjgSD0HsoCCNLp-_SurGweKnLG1qYaTxRxyjXrPqVAGg6lxIs2kjoc4VpS6kQ5Aq1oQ4l0fVh2hJu17vWo5S62V1p7lDGB6ghjMr76fbLhj9Zefw6_M1kCrTvkJ4r9-fmL3eC2nbWF5g6ssgWId8_g_5Tv74cEAqayD4kY8; expires=Wed, 16-Oct-2024 01:03:55 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-15 18:03:55,348:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 16:42:33,708:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 16:42:33,716:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 16:42:33,719:INFO:common:created directory at: artifacts]
[2024-04-23 16:42:33,721:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 16:42:33,723:INFO:986331348:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-23 16:45:51,454:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-23 17:15:27,298:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:15:27,301:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:15:27,303:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:15:27,305:INFO:common:created directory at: artifacts]
[2024-04-23 17:15:27,308:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:15:28,045:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:15:28 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=TmBN6WNo2b1CK0H6Wm6d34G55erXBy_unElDWHpKUV3-qFRBWSLasMsS52P2JglViWeWPsorG2uKBUfOTnYeDcYPXd-iRydafVH29aM-Q_SqJDicu7I0XmPLnKJiztjnPZoCdYLsFXN10_IPizuLkINwtZ_3OeGdU1AvkUIpaMs; expires=Thu, 24-Oct-2024 00:15:28 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:15:28,353:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:16:31,031:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:16:31,032:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:16:31,032:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:16:31,033:INFO:common:created directory at: artifacts]
[2024-04-23 17:16:31,034:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:16:31,533:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:16:32 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=aVSu1JibOY46utgC5WPHrdxO8zfDgu7ENEso71DE4PyuO1Z3GNxqB_4WqEixwY3piDK_UIlpaVCycJaSwj2XS-ZMNB4-NI3ZdEDTT0uv9oVWTaqvQyKw9MTK8NCNPwL50PJ43hjnqGzKRsvgVAW1J2uaqALKZWhmeHy2pKFXO28; expires=Thu, 24-Oct-2024 00:16:32 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:16:31,667:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:19:16,877:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:19:16,878:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:19:16,879:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:19:16,879:INFO:common:created directory at: artifacts]
[2024-04-23 17:19:16,880:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:19:17,379:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:19:18 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=mLV7ivdvCFgkHKHYyAZLsNobCP5MuuvmDTKsSUo0Z_xEVfN0dQrS1uGciVmEZ6_DJzVxF1ULn1V3qbraXgLFPDCzI9vaKWRaaInWxnvt9GfiEb2EfiOIlMbOHIvtCa8wwItISn_vHSNa2xUPLNWc0DYjnJQZuUSGnYf0Y-70Ns4; expires=Thu, 24-Oct-2024 00:19:17 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:19:17,506:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:19:58,716:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:19:58,718:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:19:58,719:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:19:58,719:INFO:common:created directory at: artifacts]
[2024-04-23 17:19:58,720:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:19:59,129:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:19:59 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=KM85fDwY2ZpY98GQbjiMbiP3g3l_fElf2Io3iGsOZ--nArJfzkvY4vlt4JROalfDAoj6r2meHp99_CrmZ3Fj_LdOaMn26kUA2fhrcHz1FGefsshYXtDVCwNehowpgeKUVPBRFEzwV2iPGMJZUr2xn1lAQFil0cnuQy7IlJZIvWc; expires=Thu, 24-Oct-2024 00:19:59 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:19:59,258:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:22:24,943:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:22:24,945:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:22:24,946:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:22:24,946:INFO:common:created directory at: artifacts]
[2024-04-23 17:22:24,947:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:22:25,646:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:22:26 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=YZW_IaJrdPUjLPsuhz0CKNBiEJ_CoCmu-EcjI3nf3GHwmMqtfbxWrOusMyiEOz8GCS6lQnc6l5JqvEO78utzDymW4cKMarU8mGb6lVzVQAwlvoyXAFqlAJOH526gdmpi0z1pGykXUIJuQ-bxGdYDn0iUFGiWhzbSG-67CRcAMws; expires=Thu, 24-Oct-2024 00:22:26 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:22:25,831:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:23:12,575:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:23:12,576:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:23:12,577:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:23:12,579:INFO:common:created directory at: artifacts]
[2024-04-23 17:23:12,580:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:23:13,202:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:23:13 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=W9uHWGeh5KFaaEFcD8NvJMtjXSNapto_RnxQOXPouy-S-2M32YYnkJrSN8pCrCdX6y77X2qqOAoP1YIKXA1AXZ-gQa74Md_TqSQxJRzuo-v_oV_V4uvyXhCtUGQvS2iVGrsZnsEGZWVApYQ-Fw-NyzGQgwGILIjhehemnZwPZy4; expires=Thu, 24-Oct-2024 00:23:13 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:23:13,332:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:24:10,852:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:24:10,853:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:24:10,855:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:24:10,855:INFO:common:created directory at: artifacts]
[2024-04-23 17:24:10,856:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:24:10,857:INFO:data_ingestion:File already exists of size: ~ 83 KB]
[2024-04-23 17:24:10,859:ERROR:main:File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-04-23 17:24:43,244:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:24:43,248:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:24:43,250:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:24:43,251:INFO:common:created directory at: artifacts]
[2024-04-23 17:24:43,252:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:24:43,253:INFO:data_ingestion:File already exists of size: ~ 83 KB]
[2024-04-23 17:24:43,255:ERROR:main:ZipFile requires mode 'r', 'w', 'x', or 'a']
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r+b') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1286, in __init__
    raise ValueError("ZipFile requires mode 'r', 'w', 'x', or 'a'")
ValueError: ZipFile requires mode 'r', 'w', 'x', or 'a'
[2024-04-23 17:31:14,382:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:31:14,384:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:31:14,386:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:31:14,388:INFO:common:created directory at: artifacts]
[2024-04-23 17:31:14,388:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:31:15,155:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:31:15 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=dblAxuinI3Xhc1_N5NUAbqlfEySANYmRBmAMlp2QxjbG9T0G5X34JSAGmuMSDGgJJbY05QOVz5XBlKWg-ZBK2LsNyrCmVTenDbIDYZzmgwMArHkvgV_hrQmY87wNbfqi-GLTQhINk7_Hkvuvfukteb-cJ-R7F_b-7f2cfjV4Ttw; expires=Thu, 24-Oct-2024 00:31:15 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:31:15,423:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-23 17:33:32,216:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-23 17:33:32,228:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-23 17:33:32,230:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-23 17:33:32,231:INFO:common:created directory at: artifacts]
[2024-04-23 17:33:32,233:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-23 17:33:32,822:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 00:33:33 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=Jrx46HoHDVOzLpUKQuANWhdqHUGLegpgyfoKqgSSQ2EkxaY58pTNvTgvxQHPr8dYc9A-OhO3fZhSySUfdDy47KXJmKxdySAyt90_Ozx9V-jHsnuBVynQpMo-vzB2SQpt3eicksbIR9AFg1yKEsmexrvVc4R6PWeevoDu2kQ7hno; expires=Thu, 24-Oct-2024 00:33:33 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-23 17:33:33,107:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-24 14:58:35,659:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 14:58:35,660:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 14:58:35,665:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 14:58:35,666:INFO:common:created directory at: artifacts]
[2024-04-24 14:58:35,666:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 14:58:36,332:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 21:58:36 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=Xwtk_MuJ0J_WwcBBCWdQWPpsTtkofqRuT6NaXZIbHJnBGEPOD3B7nSX2rCqeavgu5J3AN-Gl6SdAiepn_n4p4zFzEtbYwmInJgjLm2RgcHW3LSHwjN__vL9wt121gjbjHNg3xb_Lbjgzr1aijXbFm-Eae3HW7kNgRUX1kynCqOI; expires=Thu, 24-Oct-2024 21:58:36 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-24 14:58:36,491:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-24 15:04:30,900:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:04:30,901:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:04:30,902:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:04:30,903:INFO:common:created directory at: artifacts]
[2024-04-24 15:04:30,903:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:04:31,503:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 22:04:31 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=HQF_bJnkEGcbGVwsCzr947glMqKuKtZQdZ1eJpmJFS9WqpxTcFBHBez9Ssh4XWWRPqj6EQ_M9KCT_aX7GmoekUMNE537KDKOkIRD-ns3g7rYxCIt6pQbxRsqEu_Z0YFODxN3S6j_UmlZVAVNDNUvQfZLzITacOc4vdigk_m78ao; expires=Thu, 24-Oct-2024 22:04:31 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-24 15:04:31,619:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-24 15:07:00,836:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:07:00,837:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:07:00,838:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:07:00,849:INFO:common:created directory at: artifacts]
[2024-04-24 15:07:00,851:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:07:01,366:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 22:07:01 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=dd2TOtumZz2klKm_63UtM0L7D6AeiK5HBBfButYBcGrQ4-rdytQUiBw7mksnNCzNo-QR_1AnDvKXjcTtcz4AH58Gs4o56XqHWTV3S2XS3TsUE4T7Yyt3Ge1f17jv-GygT8v1miwQdCWALYWV7xW6LHc4He7cFdSkF3_nRrWWCI0; expires=Thu, 24-Oct-2024 22:07:01 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-24 15:07:01,535:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-24 15:11:23,595:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:11:23,620:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:11:23,630:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:11:23,631:INFO:common:created directory at: artifacts]
[2024-04-24 15:11:23,631:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:11:24,127:INFO:data_ingestion:artifacts/data_ingestion/data.zip download: with following info: 
 Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 24 Apr 2024 22:11:24 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=jklJ138abxVtQsC6ezFSTYQDgz4KBRGuYDjfhy4VnOS81d-x_F5eaz2l4n9y6PsefDgYXyxEt3LBnIDlND70HDKlfI7ApYbYBIpPKmZacfcVcXWnjkS6SX3NpoF05w8Sew_RJp5DpAf4Y6GICYOkExjeTYbRK4iWCqBPfrd1WXQ; expires=Thu, 24-Oct-2024 22:11:23 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-04-24 15:11:24,127:ERROR:main:ZipFile.__init__() got an unexpected keyword argument 'follow_redirects']
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 18, in main
    data_ingestion.extract_zip_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 33, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r', follow_redirects=True) as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ZipFile.__init__() got an unexpected keyword argument 'follow_redirects'
[2024-04-24 15:13:51,110:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:13:51,111:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:13:51,112:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:13:51,113:INFO:common:created directory at: artifacts]
[2024-04-24 15:13:51,113:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:13:51,113:ERROR:main:stream() got an unexpected keyword argument 'allow_redirects']
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 15, in download_file
    with httpx.stream("GET", self.config.source_URL, allow_redirects=True) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\contextlib.py", line 289, in helper
    return _GeneratorContextManager(func, args, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\contextlib.py", line 105, in __init__
    self.gen = func(*args, **kwds)
               ^^^^^^^^^^^^^^^^^^^
TypeError: stream() got an unexpected keyword argument 'allow_redirects'
[2024-04-24 15:16:59,759:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:16:59,761:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:16:59,762:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:16:59,763:INFO:common:created directory at: artifacts]
[2024-04-24 15:16:59,764:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:16:59,764:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 15:16:59,765:ERROR:main:name 'gdown' is not defined]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 8, in <module>
    data_ingestion.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.download_file()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 32, in download_file
    raise e
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\data_ingestion.py", line 27, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
    ^^^^^
NameError: name 'gdown' is not defined
[2024-04-24 15:19:17,024:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:19:17,025:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:19:17,025:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:19:17,025:INFO:common:created directory at: artifacts]
[2024-04-24 15:19:17,026:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:19:17,026:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 15:22:34,402:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 15:23:02,706:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-24 15:37:44,210:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-24 15:37:44,210:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-24 15:37:44,210:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-24 15:37:44,210:INFO:common:created directory at: artifacts]
[2024-04-24 15:37:44,210:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-24 15:37:44,210:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 15:41:04,247:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-24 15:41:23,427:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-25 23:23:24,259:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-25 23:23:24,272:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-25 23:23:24,279:INFO:common:created directory at: artifacts]
[2024-04-25 23:24:04,492:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-25 23:24:04,495:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-25 23:24:04,497:INFO:common:created directory at: artifacts]
[2024-04-25 23:24:04,499:INFO:common:created directory at: artifacts/prepare_model]
[2024-04-25 23:24:08,581:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-25 23:24:08,585:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-25 23:24:08,586:INFO:common:created directory at: artifacts]
[2024-04-25 23:24:08,588:INFO:common:created directory at: artifacts/prepare_model]
[2024-04-25 23:26:40,879:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-25 23:26:40,882:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-25 23:26:40,884:INFO:common:created directory at: artifacts]
[2024-04-25 23:26:40,886:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-04-25 23:26:47,303:WARNING:saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-25 23:46:01,056:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-25 23:46:01,058:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-25 23:46:01,061:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-25 23:46:01,061:INFO:common:created directory at: artifacts]
[2024-04-25 23:46:01,062:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-25 23:46:01,063:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-25 23:49:36,837:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-25 23:50:19,329:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-25 23:50:19,339:INFO:main:*******************]
[2024-04-25 23:50:19,342:INFO:main:>>>>>> stage Prepare Base Model started <<<<<<]
[2024-04-25 23:50:19,365:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-25 23:50:19,464:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-25 23:50:19,480:INFO:common:created directory at: artifacts]
[2024-04-25 23:50:19,605:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-04-25 23:50:20,953:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-25 23:50:21,252:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-25 23:50:21,561:INFO:main:>>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-04-27 20:55:36,969:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 20:55:36,987:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 20:55:36,991:INFO:common:created directory at: artifacts]
[2024-04-27 20:55:36,995:INFO:common:created directory at: artifacts\training]
[2024-04-27 20:57:00,199:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 20:57:00,204:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 20:57:00,208:INFO:common:created directory at: artifacts]
[2024-04-27 20:57:00,210:INFO:common:created directory at: artifacts\training]
[2024-04-27 20:59:41,100:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 20:59:41,105:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 20:59:41,108:INFO:common:created directory at: artifacts]
[2024-04-27 20:59:41,110:INFO:common:created directory at: artifacts\training]
[2024-04-27 21:00:38,550:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:00:38,553:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:00:38,556:INFO:common:created directory at: artifacts]
[2024-04-27 21:00:38,558:INFO:common:created directory at: artifacts\training]
[2024-04-27 21:01:48,731:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:01:48,734:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:01:48,736:INFO:common:created directory at: artifacts]
[2024-04-27 21:01:48,738:INFO:common:created directory at: artifacts\training]
[2024-04-27 21:10:06,050:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:10:06,056:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:10:06,059:INFO:common:created directory at: artifacts]
[2024-04-27 21:10:06,060:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-27 21:10:06,062:INFO:986331348:Downloading data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 21:12:02,345:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:12:02,350:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:12:02,352:INFO:common:created directory at: artifacts]
[2024-04-27 21:12:02,353:INFO:common:created directory at: artifacts\training]
[2024-04-27 21:13:42,901:INFO:986331348:Downloaded data from https://drive.google.com/file/d/1PY97v5ynYi_bvgfNEG3pBHcM-DZmdRJ4/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 21:14:43,846:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:14:43,850:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:14:43,853:INFO:common:created directory at: artifacts]
[2024-04-27 21:14:43,855:INFO:common:created directory at: artifacts\training]
[2024-04-27 21:51:36,582:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-27 21:51:36,584:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:51:36,585:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:51:36,586:INFO:common:created directory at: artifacts]
[2024-04-27 21:51:36,586:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-27 21:51:36,587:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1OkVOFvAYYVK2D-Ty5wePt12xXEdTjS4c/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 21:55:13,978:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1OkVOFvAYYVK2D-Ty5wePt12xXEdTjS4c/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-27 21:55:39,401:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-27 21:55:39,401:INFO:main:*******************]
[2024-04-27 21:55:39,401:INFO:main:>>>>>> stage Prepare Base Model started <<<<<<]
[2024-04-27 21:55:39,401:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:55:39,401:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:55:39,401:INFO:common:created directory at: artifacts]
[2024-04-27 21:55:39,401:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-04-27 21:55:40,000:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-27 21:55:40,152:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-27 21:55:40,304:INFO:main:>>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-04-27 21:58:25,967:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 21:58:25,974:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 21:58:25,978:INFO:common:created directory at: artifacts]
[2024-04-27 21:58:25,981:INFO:common:created directory at: artifacts\training]
[2024-04-27 22:01:02,335:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 22:01:02,340:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 22:01:02,342:INFO:common:created directory at: artifacts]
[2024-04-27 22:01:02,345:INFO:common:created directory at: artifacts\training]
[2024-04-27 22:04:45,040:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 22:04:45,044:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 22:04:45,046:INFO:common:created directory at: artifacts]
[2024-04-27 22:04:45,049:INFO:common:created directory at: artifacts\training]
[2024-04-27 22:06:14,095:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-27 22:06:14,097:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-27 22:06:14,099:INFO:common:created directory at: artifacts]
[2024-04-27 22:06:14,101:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:05:13,387:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:05:13,402:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:05:13,405:INFO:common:created directory at: artifacts]
[2024-04-28 22:05:13,409:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:24:22,979:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:24:22,987:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:24:22,991:INFO:common:created directory at: artifacts]
[2024-04-28 22:24:55,402:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:24:55,405:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:24:55,406:INFO:common:created directory at: artifacts]
[2024-04-28 22:24:55,408:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:26:14,662:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:26:14,665:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:26:14,667:INFO:common:created directory at: artifacts]
[2024-04-28 22:26:14,670:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:31:47,473:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 22:31:47,473:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:31:47,489:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:31:47,489:INFO:common:created directory at: artifacts]
[2024-04-28 22:31:47,489:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-28 22:31:47,489:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 22:31:55,120:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 22:31:55,650:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 22:31:55,650:INFO:main:*******************]
[2024-04-28 22:31:55,650:INFO:main:>>>>>> stage Prepare Base Model started <<<<<<]
[2024-04-28 22:31:55,650:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:31:55,650:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:31:55,650:INFO:common:created directory at: artifacts]
[2024-04-28 22:31:55,650:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-04-28 22:31:56,395:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-28 22:31:56,648:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-28 22:31:56,650:ERROR:main:[Errno 13] Unable to synchronously create file (unable to open file: name = 'artifacts\prepare_base_model\base_model_updated.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 21, in <module>
    prepare_base_model.main()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\pipeline\stage_02_prepare_base_model.py", line 17, in main
    prepare_base_model.update_base_model()
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\prepare_base_model.py", line 64, in update_base_model
    self.save_model(path=self.config.updated_base_model_path, model=self.full_model)
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\cnnClassifier\components\prepare_base_model.py", line 69, in save_model
    model.save(path)
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\h5py\_hl\files.py", line 562, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nandi\AppData\Roaming\Python\Python312\site-packages\h5py\_hl\files.py", line 241, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py\\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\\h5f.pyx", line 122, in h5py.h5f.create
PermissionError: [Errno 13] Unable to synchronously create file (unable to open file: name = 'artifacts\prepare_base_model\base_model_updated.h5', errno = 13, error message = 'Permission denied', flags = 13, o_flags = 302)
[2024-04-28 22:34:21,883:INFO:main:>>>>>> stage Data Ingestion stage started <<<<<<]
[2024-04-28 22:34:21,883:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:34:21,900:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:34:21,900:INFO:common:created directory at: artifacts]
[2024-04-28 22:34:21,900:INFO:common:created directory at: artifacts/data_ingestion]
[2024-04-28 22:34:21,900:INFO:data_ingestion:Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 22:34:29,214:INFO:data_ingestion:Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-28 22:34:29,878:INFO:main:>>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-04-28 22:34:29,878:INFO:main:*******************]
[2024-04-28 22:34:29,878:INFO:main:>>>>>> stage Prepare Base Model started <<<<<<]
[2024-04-28 22:34:29,878:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:34:29,878:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:34:29,878:INFO:common:created directory at: artifacts]
[2024-04-28 22:34:29,878:INFO:common:created directory at: artifacts/prepare_base_model]
[2024-04-28 22:34:30,214:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-28 22:34:30,314:WARNING:saving_api:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2024-04-28 22:34:30,377:INFO:main:>>>>>> stage Prepare Base Model completed <<<<<<

x==========x]
[2024-04-28 22:35:58,859:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:35:58,864:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:35:58,868:INFO:common:created directory at: artifacts]
[2024-04-28 22:35:58,870:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:36:49,525:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:36:49,527:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:36:49,529:INFO:common:created directory at: artifacts]
[2024-04-28 22:36:49,530:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:42:28,905:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:42:28,908:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:42:28,911:INFO:common:created directory at: artifacts]
[2024-04-28 22:42:28,913:INFO:common:created directory at: artifacts\training]
[2024-04-28 22:47:58,430:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-28 22:47:58,433:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-28 22:47:58,434:INFO:common:created directory at: artifacts]
[2024-04-28 22:47:58,437:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:18:14,551:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:18:14,566:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:18:14,569:INFO:common:created directory at: artifacts]
[2024-04-29 21:18:14,572:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:27:29,253:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:27:29,260:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:27:29,262:INFO:common:created directory at: artifacts]
[2024-04-29 21:27:29,263:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:27:58,338:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:27:58,348:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:27:58,350:INFO:common:created directory at: artifacts]
[2024-04-29 21:27:58,351:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:32:46,303:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:32:46,317:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:32:46,321:INFO:common:created directory at: artifacts]
[2024-04-29 21:32:46,324:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:34:23,491:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:34:23,494:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:34:23,496:INFO:common:created directory at: artifacts]
[2024-04-29 21:34:23,498:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:51:26,839:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:51:26,842:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:51:26,845:INFO:common:created directory at: artifacts]
[2024-04-29 21:51:26,847:INFO:common:created directory at: artifacts\training]
[2024-04-29 21:58:17,426:INFO:common:yaml file: config\config.yaml loaded successfully]
[2024-04-29 21:58:17,430:INFO:common:yaml file: params.yaml loaded successfully]
[2024-04-29 21:58:17,431:INFO:common:created directory at: artifacts]
[2024-04-29 21:58:17,433:INFO:common:created directory at: artifacts\training]
[2024-05-01 15:57:11,673: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 15:57:11,677: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 15:57:11,684: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 15:57:11,692: INFO: common: created directory at: artifacts]
[2024-05-01 15:57:11,693: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 15:57:12,417: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 01 May 2024 22:57:13 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=AlNgAXYGif3FQMXUFjacBmLeN3QgQw3-JeHUXs1ZPQgIRHLw-m0CQcOBrvKbCY15pqk39k0nDlp43VRFyMKNnuVeAoYUeYb8U9hK7vwipRODejS-nPMRcGiTibH5838VLVsrbidAWRkLhtbntegCtvH8Z1auyYwS0OspUDHpTms; expires=Thu, 31-Oct-2024 22:57:13 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-05-01 15:57:12,566: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 10, in <module>
    data_ingestion.main()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-05-01 15:57:42,348: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 15:57:42,374: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 15:57:42,374: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 15:57:42,374: INFO: common: created directory at: artifacts]
[2024-05-01 15:57:42,374: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 15:57:43,066: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 01 May 2024 22:57:44 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=LjBJ7bell7uGwyzU75H_aGG98vl6K8QG8tD1w71ik9YqKIzseFusToqy9FDNR2NOwv-fFTQzJFB3q8E_IDxiOoRau-Nsvjc3L450dfFaJDwyWL9jP4mVzpeRpY99ZyxeVNNyqv1uuCpj2wD4kEqvJpePyjWRm8xw-L_DT7Y0cyA; expires=Thu, 31-Oct-2024 22:57:43 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-05-01 15:57:43,150: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 10, in <module>
    data_ingestion.main()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-05-01 16:00:01,078: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 16:00:01,078: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 16:00:01,078: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 16:00:01,078: INFO: common: created directory at: artifacts]
[2024-05-01 16:00:01,078: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 16:00:01,078: INFO: data_ingestion: File already exists of size: ~ 84 KB]
[2024-05-01 16:00:01,092: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 10, in <module>
    data_ingestion.main()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
[2024-05-01 16:00:30,794: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-05-01 16:00:30,796: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-05-01 16:00:30,796: INFO: common: yaml file: params.yaml loaded successfully]
[2024-05-01 16:00:30,796: INFO: common: created directory at: artifacts]
[2024-05-01 16:00:30,803: INFO: common: created directory at: artifacts/data_ingestion]
[2024-05-01 16:00:31,473: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Content-Type: text/html; charset=utf-8
X-Robots-Tag: noindex, nofollow, nosnippet
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Wed, 01 May 2024 23:00:32 GMT
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: require-trusted-types-for 'script';report-uri https://csp.withgoogle.com/csp/docs-tt
Referrer-Policy: origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=513=lEaXcnBcs1H3ZQSXmnfMywUOApEsE_OxUiL2X6BuEwPCd0NxHzJg-DRxehV-zPYInAdjNwSnQvSDtEMF7BBOdYtwINJk3hvlCq5Bun4lWGeIzpGI6i2wogYfbACQBpz9iBnQsIplY8dfPNaHNCRVIPsW-amLxPdmjeQL6ocvnHo; expires=Thu, 31-Oct-2024 23:00:32 GMT; path=/; domain=.google.com; HttpOnly
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Accept-Ranges: none
Vary: Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site,Accept-Encoding
Connection: close
Transfer-Encoding: chunked

]
[2024-05-01 16:00:31,574: ERROR: main: File is not a zip file]
Traceback (most recent call last):
  File "E:\COVID-Prediction-Classification-Project\main.py", line 10, in <module>
    data_ingestion.main()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 17, in main
    data_ingestion.extract_zip_file()
  File "e:\chicken-disease-classification--project\src\cnnClassifier\components\data_ingestion.py", line 36, in extract_zip_file
    with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1338, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python312\Lib\zipfile\__init__.py", line 1405, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
